import type { Metadata } from "next";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";
import Footer from "@/components/Footer";
import { PopupProvider } from "@/context/PopupContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        <PopupProvider>
          <div className="flex">
            <Sidebar />
            <div className="w-full relative">
              <Header />
              <div className="p-10">{children}</div>
              <div className="absolute bottom-0 w-full">
                <Footer />
              </div>
            </div>
          </div>
        </PopupProvider>
      </body>
    </html>
  );
}
