import type { Metadata } from "next";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";
import Footer from "@/components/Footer";
import { PopupProvider } from "@/context/PopupContext";
import { Bai_Jamjuree } from "next/font/google";

export const metadata: Metadata = {
  title: "จัดเก็บและสืบค้นโครงงาน คณะบริหารธุรกิจ มทร.อีสาน",
  description: "Generated by create next app",
  icons: "/favicon.ico",
};

const baiJamjuree = Bai_Jamjuree({
  subsets: ["thai", "latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        <div
          className={`${baiJamjuree.className} flex flex-1 flex-wrap lg:flex-nowrap`}
        >
          <PopupProvider>
            {/* Sidebar */}
            <div
              className={`z-10 drop-shadow-lg sticky top-0 bg-white hidden
              lg:flex lg:flex-col lg:w-[300px] lg:p-3 lg:h-screen lg:overflow-auto
              2xl:w-[400px] 2xl:p-5
            `}
            >
              <Sidebar />
            </div>

            {/* Main Content */}
            <div className="flex flex-col flex-1 min-w-0">
              <Header />
              <div
                className="flex-1 overflow-auto p-2
                lg:p-5
                2xl:p-10
              "
              >
                {children}
              </div>
              <Footer />
            </div>
          </PopupProvider>
        </div>
      </body>
    </html>
  );
}
